### PR TITLE
Docs fix

### LINKED ISSUE #26: Fix all warnings and mistakes in documentation
For check warnings and errors user the [DocGeneratorBuilder](https://quasarapp.ddns.net:8043/#/builders/9)
Warnings prints in the " Generate docs for the project " step.

When all warning will be fixed then check docs site using the "copy buildet files" step of the buildbot.

### PR DESCRIPTION
**Pull request by Oleg-designer**
fix #26

### CODE REVIEW

File: params.h [hunk 1]
```diff
@@ -51,69 +51,69 @@ class QUASARAPPSHARED_EXPORT Params
...
     static bool isEndable(const QString& key);
 
     /**
-     * @brief log - print text on console if the flag "vergose" is enabled
-     * @param log - printed text
+     * @brief log Print text on console if the flag "vergose" is enabled.
+     * @param log Printed textP.     
      */
-    static void log(const QString& log, VerboseLvl vLvl = VerboseLvl::Debug);
+    static void log(const QStrinP& log, VerboseLvl vLvl = VerboseLvl::Debug);
```
Comment (EndrII) [inline params.h:101]: This line is broken all builds.
You do not can change source code, you can change only documentation comments. 
```suggestion
    static void log(const QString& log, VerboseLvl vLvl = VerboseLvl::Debug);
```

**Review by EndrII — CHANGES_REQUESTED** [review]

**Review by EndrII — APPROVED** [review]
I Think this PR can be merged
